"""Static initial Talk2Dashboard storage schema.

Revision ID: 0001
Revises:
Create Date: 2026-07-11 01:33:05.904400
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("asset_handle", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("suffix", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("asset_handle"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_table(
        "budget_counters",
        sa.Column("counter_key", sa.String(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("counter_key", "day"),
    )
    op.create_table(
        "conversation_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("turn_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("final", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("dashboard_version", sa.Integer(), nullable=True),
        sa.Column("source_bundle_version", sa.String(), nullable=True),
        sa.Column("handle_ids_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_conversation_events_conversation_id"),
        "conversation_events",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_events_created_at"),
        "conversation_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_events_role"), "conversation_events", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_events_turn_id"), "conversation_events", ["turn_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=False),
        sa.Column("ended_at", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("voice_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_table(
        "dashboard_configs",
        sa.Column("config_version_id", sa.String(), nullable=False),
        sa.Column("dashboard_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("previous_version", sa.Integer(), nullable=True),
        sa.Column("spec_json", sa.Text(), nullable=False),
        sa.Column("json_patch", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=True),
        sa.Column("turn_id", sa.String(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_bundle_version", sa.String(), nullable=False),
        sa.Column("logical_binding_ids_json", sa.Text(), nullable=False),
        sa.Column("last_rendered_source_bundle_version", sa.String(), nullable=True),
        sa.Column("last_rendered_handle_ids_json", sa.Text(), nullable=False),
        sa.Column("renderer_status", sa.String(), nullable=False),
        sa.Column("screenshot_handle", sa.String(), nullable=True),
        sa.Column("restored_from_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("config_version_id"),
    )
    op.create_index(
        op.f("ix_dashboard_configs_dashboard_id"),
        "dashboard_configs",
        ["dashboard_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dashboard_configs_version"), "dashboard_configs", ["version"], unique=False
    )
    op.create_table(
        "data_handles",
        sa.Column("handle_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("source_bundle_version", sa.String(), nullable=False),
        sa.Column("query_hash", sa.String(), nullable=False),
        sa.Column("schema_fingerprint", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("handle_id"),
    )
    op.create_index(op.f("ix_data_handles_kind"), "data_handles", ["kind"], unique=False)
    op.create_index(
        op.f("ix_data_handles_query_hash"), "data_handles", ["query_hash"], unique=False
    )
    op.create_index(
        op.f("ix_data_handles_source_bundle_version"),
        "data_handles",
        ["source_bundle_version"],
        unique=False,
    )
    op.create_table(
        "incident_clusters",
        sa.Column("incident_version_id", sa.String(), nullable=False),
        sa.Column("incident_id", sa.String(), nullable=False),
        sa.Column("bundle_version", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.String(), nullable=False),
        sa.Column("last_seen_at", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("incident_version_id"),
    )
    op.create_index(
        op.f("ix_incident_clusters_bundle_version"),
        "incident_clusters",
        ["bundle_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_clusters_incident_id"), "incident_clusters", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_incident_clusters_status"), "incident_clusters", ["status"], unique=False
    )
    op.create_table(
        "latency_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=True),
        sa.Column("turn_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("monotonic_ns", sa.Integer(), nullable=False),
        sa.Column("wall_clock", sa.String(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_latency_events_conversation_id"),
        "latency_events",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_latency_events_event_type"), "latency_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_latency_events_turn_id"), "latency_events", ["turn_id"], unique=False)
    op.create_table(
        "provider_calls",
        sa.Column("call_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("usage_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(
        op.f("ix_provider_calls_created_at"), "provider_calls", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_provider_calls_operation"), "provider_calls", ["operation"], unique=False
    )
    op.create_index(
        op.f("ix_provider_calls_provider"), "provider_calls", ["provider"], unique=False
    )
    op.create_table(
        "render_states",
        sa.Column("dashboard_id", sa.String(), nullable=False),
        sa.Column("dashboard_version", sa.Integer(), nullable=False),
        sa.Column("source_bundle_version", sa.String(), nullable=False),
        sa.Column("handle_ids_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("dashboard_id"),
    )
    op.create_table(
        "session_policy",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("web_search_enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_update_enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("singleton_id"),
    )
    op.create_table(
        "source_bundles",
        sa.Column("bundle_version", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("snapshot_ids_json", sa.Text(), nullable=False),
        sa.Column("health_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("bundle_version"),
    )
    op.create_table(
        "source_snapshots",
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("stream_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.String(), nullable=False),
        sa.Column("ingested_at", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_index(
        op.f("ix_source_snapshots_stream_id"), "source_snapshots", ["stream_id"], unique=False
    )
    op.create_table(
        "tool_audit",
        sa.Column("audit_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=True),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("arguments_json", sa.Text(), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("started_ns", sa.Integer(), nullable=False),
        sa.Column("ended_ns", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("dashboard_before", sa.Integer(), nullable=True),
        sa.Column("dashboard_after", sa.Integer(), nullable=True),
        sa.Column("source_bundle_version", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        op.f("ix_tool_audit_conversation_id"), "tool_audit", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_tool_audit_created_at"), "tool_audit", ["created_at"], unique=False)
    op.create_index(op.f("ix_tool_audit_request_id"), "tool_audit", ["request_id"], unique=True)
    op.create_index(op.f("ix_tool_audit_tool_name"), "tool_audit", ["tool_name"], unique=False)
    op.create_table(
        "normalized_record_versions",
        sa.Column("record_version_id", sa.String(), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("stream_id", sa.String(), nullable=False),
        sa.Column("record_kind", sa.String(), nullable=False),
        sa.Column("observed_at", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshots.snapshot_id"],
        ),
        sa.PrimaryKeyConstraint("record_version_id"),
    )
    op.create_index(
        op.f("ix_normalized_record_versions_observed_at"),
        "normalized_record_versions",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_record_versions_record_id"),
        "normalized_record_versions",
        ["record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_record_versions_record_kind"),
        "normalized_record_versions",
        ["record_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_record_versions_snapshot_id"),
        "normalized_record_versions",
        ["snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_record_versions_stream_id"),
        "normalized_record_versions",
        ["stream_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_normalized_record_versions_stream_id"), table_name="normalized_record_versions"
    )
    op.drop_index(
        op.f("ix_normalized_record_versions_snapshot_id"), table_name="normalized_record_versions"
    )
    op.drop_index(
        op.f("ix_normalized_record_versions_record_kind"), table_name="normalized_record_versions"
    )
    op.drop_index(
        op.f("ix_normalized_record_versions_record_id"), table_name="normalized_record_versions"
    )
    op.drop_index(
        op.f("ix_normalized_record_versions_observed_at"), table_name="normalized_record_versions"
    )
    op.drop_table("normalized_record_versions")
    op.drop_index(op.f("ix_tool_audit_tool_name"), table_name="tool_audit")
    op.drop_index(op.f("ix_tool_audit_request_id"), table_name="tool_audit")
    op.drop_index(op.f("ix_tool_audit_created_at"), table_name="tool_audit")
    op.drop_index(op.f("ix_tool_audit_conversation_id"), table_name="tool_audit")
    op.drop_table("tool_audit")
    op.drop_index(op.f("ix_source_snapshots_stream_id"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_table("source_bundles")
    op.drop_table("session_policy")
    op.drop_table("render_states")
    op.drop_index(op.f("ix_provider_calls_provider"), table_name="provider_calls")
    op.drop_index(op.f("ix_provider_calls_operation"), table_name="provider_calls")
    op.drop_index(op.f("ix_provider_calls_created_at"), table_name="provider_calls")
    op.drop_table("provider_calls")
    op.drop_index(op.f("ix_latency_events_turn_id"), table_name="latency_events")
    op.drop_index(op.f("ix_latency_events_event_type"), table_name="latency_events")
    op.drop_index(op.f("ix_latency_events_conversation_id"), table_name="latency_events")
    op.drop_table("latency_events")
    op.drop_index(op.f("ix_incident_clusters_status"), table_name="incident_clusters")
    op.drop_index(op.f("ix_incident_clusters_incident_id"), table_name="incident_clusters")
    op.drop_index(op.f("ix_incident_clusters_bundle_version"), table_name="incident_clusters")
    op.drop_table("incident_clusters")
    op.drop_index(op.f("ix_data_handles_source_bundle_version"), table_name="data_handles")
    op.drop_index(op.f("ix_data_handles_query_hash"), table_name="data_handles")
    op.drop_index(op.f("ix_data_handles_kind"), table_name="data_handles")
    op.drop_table("data_handles")
    op.drop_index(op.f("ix_dashboard_configs_version"), table_name="dashboard_configs")
    op.drop_index(op.f("ix_dashboard_configs_dashboard_id"), table_name="dashboard_configs")
    op.drop_table("dashboard_configs")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_conversation_events_turn_id"), table_name="conversation_events")
    op.drop_index(op.f("ix_conversation_events_role"), table_name="conversation_events")
    op.drop_index(op.f("ix_conversation_events_created_at"), table_name="conversation_events")
    op.drop_index(op.f("ix_conversation_events_conversation_id"), table_name="conversation_events")
    op.drop_table("conversation_events")
    op.drop_table("budget_counters")
    op.drop_table("assets")
    # ### end Alembic commands ###
